<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function testSingle($name = 'A')
    {
        /**
         * Entity manager
         */
        $em = $this->getEntityManager();
        /**
         * Query builder
        */
        $qb = $em->createQueryBuilder();
        /**
         * Create query
        */
        $qb
        ->select('Person')
        ->from('AppBundle:Person', 'Person')
        ->where(
            $qb->expr()
            ->like('Person.name', ':name'))
            ->setParameter('name', $name)
        ;
        $query = $qb->getQuery();
    
        return $query->getResult();
    }
    
}
